red_objects: 2
red_0:
    pose: [-0.2,-0.2,0.102,0,0,0]
    frame_id: surface_1
red_1:
    pose: [-0.07,-0.05,0.102,0,0,0]
    frame_id: surface_1

green_objects: 2
green_0:
    pose: [-0.20,0.15,0.102,0,0,0]
    frame_id: surface_1
green_1:
    pose: [0.07,0.07,0.102,0,0,0]
    frame_id: surface_1

blue_objects: 2
blue_0:
    pose: [-0.15,0.17,0.102,0,0,0]
    frame_id: surface_1
blue_1:
    pose: [-0.01,0.07,0.102,0,0,0]
    frame_id: surface_1

yellow_objects: 2
yellow_0:
    pose: [0.02,-0.12,0.102,0,0,0]
    frame_id: surface_1
yellow_1:
    pose: [-0.19,0.01,0.102,0,0,0]
    frame_id: surface_1


red_targets: 2
red_target_0:
    pose: [0.07,-0.2,0.102,0,0,0]
    frame_id: table_1
red_target_1:
    pose: [-0.07,-0.2,0.102,0,0,0]
    frame_id: table_1

green_targets: 2
green_target_0:
    pose: [0.07,-0.05,0.102,0,0,0]
    frame_id: table_1
green_target_1:
    pose: [-0.07,-0.05,0.102,0,0,0]
    frame_id: table_1

blue_targets: 2
blue_target_0:
    pose: [0.07,0.2,0.102,0,0,0]
    frame_id: table_2
blue_target_1:
    pose: [-0.07, 0.2,0.102,0,0,0]
    frame_id: table_2

yellow_targets: 2
yellow_target_0:
    pose: [0.07,0.05,0.102,0,0,0]
    frame_id: table_2
yellow_target_1:
    pose: [-0.07,0.05,0.102,0,0,0]
    frame_id: table_2
